- .github/workflows/test.yml
- lib/stdlib/src/encode_zstd.rs
- lib/stdlib/src/lib.rs
- lib/tests/tests/functions/zstd.vrl
- lib/value/src/lib.rs
- adds some basic CI tests (more will come later)
- fixed some failing tests since `Cargo.lock` was removed (since this is a library)
- zstd tests asserts exact binary output, which changed with a version bump (tests changed to assert it can still decode)
- deprecations are allowed, since minor version bumps can fail CI. A different approach may be needed here in the future.
> chore: add basic CI tests

- .github/workflows/test.yml
- lib/stdlib/benches/benches.rs
closes https://github.com/vectordotdev/vrl/issues/154
This makes clippy fail CI if a warning is generated. I'm not entirely sure this makes sense for a library, since dependency updates could introduce arbitrary warnings and cause CI to fail, but we will try it out and remove it / pick a different strategy if it doesn't work out.
> chore: make clippy fail on warnings

- CHANGELOG.md
- lib/stdlib/src/split.rs
Note: This was migrated to the VRL repo from https://github.com/vectordotdev/vector/pull/16874
Fixes: https://github.com/vectordotdev/vrl/issues/34
- adds guard for limit to be a positive value (following [similar behavior of truncate](https://github.com/vectordotdev/vector/blob/master/lib/vrl/stdlib/src/truncate.rs#L7) to treat negative values as 0)
- adds unit tests around limit values
Before:
```
$ split("This is a long string", " ",  -10000)
["This", "is", "a", "long", "string"]
```
After:
```
$ split("This is a long string", " ",  0)
[]
$ split("This is a long string", " ",  -10000)
[]
```
> fix(vrl): Add guard for limit in split() fn to be positive

- CHANGELOG.md
- lib/stdlib/src/match.rs
I'd like to reduce the load of Vector using complicated patterns for match functions, e.g., complex multiline regexes. The `match_any` accepts only static regexes and precompiles them into regex set. Thus, for complicated patterns, `match_any` can outperform simple `match`.
This PR implements the idea that static and dynamic arguments can be distinguished at the compile time, and all static regular expressions can be precompiled. 
The same approach can be applied to the `match_array` function in the future (probably in the scope of another PR).
For example, the first line always starts with a date/time when detecting a multiline.
```yaml
starts_when: '^\[?((((19|20)([2468][048]|[13579][26]|0[48])|2000)-02-29|((19|20)[0-9]{2}-(0[4678]|1[02])-(0[1-9]|[12][0-9]|30)|(19|20)[0-9]{2}-(0[1359]|11 …
```
> feat(stdlib): Precompile static regular expressions

- lib/web-playground/Cargo.toml
closes: https://github.com/vectordotdev/vrl/issues/16
Since the other random functions (e.g. `random_bool`) seem to work on the playground now, `random_bytes` should also work.
> enhancement: add `random_bytes` to the web playground

- CHANGELOG.md
This commit will be tagged with `0.2.0` after being merged. Note that crate versions are not being versioned yet, we are only using git tags for the entire repo.
> chore: release `0.2.0`

- CHANGELOG.md
- lib/lookup/src/lookup_v2/owned.rs
- lib/value/Cargo.toml
- lib/value/src/kind/collection/field.rs
- lib/value/src/kind/debug.rs
`Field` is just a newtype wrapper around the value of a field, which is just a String. The only thing somewhat complicated here was the `Display` impl. Ideally this would re-use the path parsing logic to detect if quotes are needed when displaying the value, but the parser is currently lenient in what it accepts so not all "invalid" field values would be quoted correctly. The regex matcher was re-used from `FieldBuf`. This is not something that's used in performance critical code.
> chore: remove deprecated `FieldBuf` from `Field`

- lib/tests/Cargo.toml
- lib/tests/src/lib.rs
- lib/tests/src/main.rs
- lib/tests/src/test.rs
This is a continuation of work to remove dependencies on the `vrl` crate to avoid circular dependencies when the root `vrl` crate starts re-exporting this functionality.
> chore: remove `vrl` as a dependency of the `tests` crate

- Cargo.toml
- lib/compiler/src/test_util.rs
- lib/stdlib/Cargo.toml
- lib/stdlib/benches/benches.rs
- lib/stdlib/src/del.rs
- lib/stdlib/src/merge.rs
- lib/stdlib/src/to_timestamp.rs
- lib/stdlib/src/unnest.rs
- lib/stdlib/src/uuid_v4.rs
- src/lib.rs
This is the last `vrl` dependency in VRL.
> chore: remove `vrl` as a dev-dependency of the `stdlib` crate

- lib/path/src/lib.rs
The recent `path` crate renaming broke some macros. These were fixed, and tests were added to prevent this in the future.
> fix: Fix path macros and add tests

- .github/workflows/test.yml
- LICENSE-3rdparty.csv
This adds a generated `LICENSE-3rdparty.csv` file mandated by DataDog's open source policy, as well as a CI step to check that the file is up to date.
> chore: Set up 3rd party license list file

- LICENSE-3rdparty.csv
Seems to be due to some changes to the license tool itself since previous commits passed.
> chore: Regenerate license inventory

- Cargo.toml
This was the only required dependency. It's only needed for compiling with WASM. Instead of depending on it directly, the "js" feature flag is used with the `uuid` crate.
> chore: remove `getrandom` dependency

- lib/tests/tests/expressions/query/container_side_effect.vrl
- lib/tests/tests/expressions/query/function_side_effect.vrl
- src/compiler/expression/query.rs
- src/compiler/state.rs
closes https://github.com/vectordotdev/vrl/issues/239
queries in VRL can query both functions and "containers" (arbitrary code blocks), which can contain side-effects. These side-effects were not captured in the type definition.
> fix: typedefs with query side-effects

- CHANGELOG.md
- LICENSE-3rdparty.csv
- lib/fuzz/src/main.rs
- src/cli/repl.rs
- src/compiler/expression/assignment.rs
- src/compiler/program.rs
closes: https://github.com/vectordotdev/vrl/issues/240
The type definition of both the result and target of VRL programs is known, but only the target was exposed to users. This gives access to both. It is a minor breaking change.
This is useful for things such as Vector VRL conditions to be able to verify at compile time that programs return a boolean. It will also help with fuzz testing.
> feat: give access to the program result type definition

- CHANGELOG.md
- CONTRIBUTING.md
- src/parser/lex.rs
New PR (previous one -> https://github.com/vectordotdev/vrl/pull/219), had to make a new one because of conflicts.
Partially solves https://github.com/vectordotdev/vrl/issues/148
added supported null \0 escape character to new lexer
> Added null escape to lexer

- CHANGELOG.md
- src/stdlib/from_unix_timestamp.rs
- src/stdlib/mod.rs
closes: #188
Contains unit tests. Also, tested with REPL:
```
.t = from_unix_timestamp!(5)
t'1970-01-01T00:00:05Z'
.t = from_unix_timestamp!(5, unit: "nanoseconds")
t'1970-01-01T00:00:00.000000005Z'
.t = from_unix_timestamp!(5.1)
error[E110]: invalid argument type
┌─ :1:27
```
This introduces some code duplication with `stdlib/to_timestamp.rs` but the latter will be deprecated soon.
> feat: add from_unix_timestamp function

- CHANGELOG.md
- src/core/encode_key_value.rs
Fixes: https://github.com/vectordotdev/vector/issues/17855
> fix(encode_logfmt): correctly handle values with equal signs

- .github/workflows/test.yml
> chore: Install dd-rust-license-tool from crates.io

- build.rs
Hi, noticed that `vrl` crate was always rebuilding.
Found out the `cargo:rerun-if-changed` had wrong path. Fixed it.
> Fix always rebuilding because of build.rs

- lib/tests/src/main.rs
- src/test/mod.rs
- src/test/test.rs
Currently the test discovery depends on the current working dir. The goal of this PR is to make it work independently of where the tests are run.
On master branch:
``` 
cd /path/to/vrl/
cargo run --package vrl-tests --bin vrl-tests
.
.
.
Overall result: SUCCESS
Number passed: 379
```
Note: IDEs generate the above command.
On this branch:
```
cargo run --package vrl-tests --bin vrl-tests
.
.
.
Overall result: SUCCESS
Number passed: 643
```
Another way to run the tests is:
```
cd path/to/vrl/lib/tests
cargo run
.
.
.
Overall result: SUCCESS
Number passed: 643
```
Note the above works already, the problem only appears when using the different method above.
Another tiny improvement is that I added an `uncategorized` category:
```
uncategorized …
```
> fix: VRL tests glob now returns all tests locally

- CHANGELOG.md
- src/stdlib/encode_json.rs
Add `pretty` parameter for `encode_json` function to produce pretty-printed JSON string.
closes #358
> enhancement: Add `pretty` parameter for `encode_json`

- CHANGELOG.md
- src/stdlib/encode_gzip.rs
- src/stdlib/encode_zlib.rs
closes: https://github.com/vectordotdev/vrl/issues/257
This now ensures the compression level is valid to prevent a panic. The type def was updated to be fallible only if it's not known at compile-time to be valid.
> fix: check compression level in `encode_zlib` and `encode_gzip`

- CHANGELOG.md
- lib/tests/tests/expressions/literal/array_undefined_upgrade copy.vrl
- lib/tests/tests/expressions/literal/object_undefined_upgrade.vrl
- src/compiler/expression/array.rs
- src/compiler/expression/object.rs
- src/compiler/type_def.rs
closes https://github.com/vectordotdev/vrl/issues/241 for both array and object literals
> fix: typedef of array/object literals containing undefined values

- CHANGELOG.md
- src/stdlib/parse_aws_vpc_flow_log.rs
REF: https://github.com/vectordotdev/vrl/issues/263
Changed field `account_id` from an Integer type to a string.
As stated in [VPC Flow Log documentation](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-fields), account-id is labelled as a string type. It is also stated that this field may have a value of `unknown`. Some account ID's may have leading zeros, which would be dropped during conversion to integer.
> fix: vpc flow log field account-id as string

- CHANGELOG.md
- src/stdlib/parse_aws_vpc_flow_log.rs
REF: https://github.com/vectordotdev/vrl/issues/227
Updated the fields for `parse_aws_vpc_flow_log` to include the latest version 5 fields. Reference to the new fields can be found here: https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-fields
Added tests from the version 5 example logs: https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-records-examples.html#flow-log-example-traffic-path
Ran checks and confirmed passed.
> fix: update AWS VPC Flow Log fields to version 5

- CHANGELOG.md
- src/stdlib/log_util.rs
- src/stdlib/parse_nginx_log.rs
Since the fields can be empty in some circustances, it is better to use '*' instead of '+' to match the values.
Below is an example log from our Nginx container which can fail the `parse_nginx_log()` finction:
```
2023/09/08 13:50:28 [warn] 3#3: *531 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/fastcgi/6/03/0000000036 while reading upstream, client: 140.113.168.124, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "duty.cs.nctu.edu.tw", referrer: "https://oauth.cs.nctu.edu.tw/"
```
> Loosen Nginx error log regex matching

- scripts/clippy.sh
- scripts/tests.sh
- src/path/mod.rs
- src/value/value.rs
We can now run `cargo test` or `cargo clippy` without `--features "tests"`.
> chore: standard cargo commands work without requiring the 'test' feature

- CHANGELOG.md
- Cargo.lock
- benches/stdlib.rs
- src/compiler/compiler.rs
- src/stdlib/truncate.rs
closes: https://github.com/vectordotdev/vrl/issues/438
This preserves backwards compatibility with the existing function signature and behavior.
> feat: replace 'truncate' ellipsis argument with user defined suffix

- CHANGELOG.md
- src/stdlib/from_unix_timestamp.rs
- src/stdlib/to_unix_timestamp.rs
> feat(stdlib): support microseconds in from_unix_timestamp

- CHANGELOG.md
- src/stdlib/log_util.rs
- src/stdlib/parse_nginx_log.rs
There's a valid use case when `upstream_response_length`, `upstream_response_time`, `upstream_status` are sometimes unavailable but the rest of the log message still matches the `upstreaminfo` format (e.g. static files served by the same virtual host). Here's an example of such a message:
```
1.1.1.1 - - [09/Oct/2023:10:49:43 +0200] "GET /media/cache/f4/b4/f4b494deadbeefc8.jpg HTTP/1.1" 200 32235 "https://example.com/page/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" 951 0.000 [upstream-production-service-1234] [upstream-production-service-1234] - - - - 7d1f3deadbeefcbb3bc
```
Currently, this kind of message generates a parsing error and some logging data is lost. It would be useful if instead the rest of the available …
> enhancement: allow more missing upstream info in parse_nginx_log

- CHANGELOG.md
- src/stdlib/mod.rs
- src/stdlib/parse_float.rs
New VRL function  `parse_float()` to parse float string. Using `f64::from_str()` in the standard library as underlying implementation.
Close #266
> Add parse_float() VRL function

- CHANGELOG.md
- lib/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
- lib/tests/tests/examples/blog_vector_remap_language_error_diagnostic.vrl
- src/compiler/expression/assignment.rs
- src/diagnostic/mod.rs
- src/diagnostic/note.rs
part of https://github.com/vectordotdev/vrl/issues/23
> feat(diagnostics): improve fallibility error notes

- Cargo.lock
> chore(deps): Remove dependency on yanked lalrpop-util version

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- src/stdlib/decode_snappy.rs
- src/stdlib/encode_snappy.rs
- src/stdlib/mod.rs
* add 'encode_snappy' and 'decode_snappy'
I have to deal with snappy encoded messages and this function would help me a lot!
> feature(stdlib): add snappy codec

- lib/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
- lib/tests/tests/examples/blog_vector_remap_language_error_diagnostic.vrl
- src/compiler/compiler.rs
- src/compiler/expression.rs
- src/compiler/expression/abort.rs
- src/compiler/expression/assignment.rs
- src/compiler/expression/function_call.rs
- src/compiler/expression/op.rs
- src/compiler/expression_error.rs
- src/compiler/function/closure.rs
- src/compiler/mod.rs
- src/compiler/prelude.rs
- src/compiler/runtime.rs
- src/compiler/value/arithmetic.rs
- src/compiler/value/error.rs
- src/diagnostic/mod.rs
- src/stdlib/assert.rs
- src/stdlib/assert_eq.rs
- src/stdlib/community_id.rs
- src/stdlib/decode_mime_q.rs
- src/stdlib/match.rs
- src/stdlib/match_datadog_query.rs
- src/stdlib/parse_json.rs
- src/stdlib/wasm_unsupported_function.rs
> feat(diagnostics): improve assignment fallibility compilation error

- src/compiler/expression.rs
- src/compiler/expression/abort.rs
- src/compiler/expression/function_call.rs
- src/compiler/expression_error.rs
- src/compiler/function/closure.rs
- src/compiler/mod.rs
- src/compiler/prelude.rs
- src/compiler/runtime.rs
- src/compiler/value/arithmetic.rs
- src/compiler/value/error.rs
- src/stdlib/assert.rs
- src/stdlib/assert_eq.rs
- src/stdlib/community_id.rs
- src/stdlib/decode_mime_q.rs
- src/stdlib/match.rs
- src/stdlib/match_datadog_query.rs
- src/stdlib/parse_json.rs
- src/stdlib/wasm_unsupported_function.rs
ref: #23, [OPW-89](https://datadoghq.atlassian.net/browse/OPW-89)
[OPW-89]: https://datadoghq.atlassian.net/browse/OPW-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(refactor): merge 'ExpressionError' and 'ExpressionError2'

- lib/tests/tests/diagnostics/unhandled_parse_regex_all_type.vrl
- lib/tests/tests/examples/blog_vector_remap_language_error_diagnostic.vrl
- src/compiler/expression/assignment.rs
> feat(diagnostics): improve fallibility assignment error

- CHANGELOG.md
- lib/tests/tests/functions/parse_regex_all.vrl
- src/stdlib/parse_regex_all.rs
closes: #562 
Tested with 
```
regex_list = [ r'pattern1', r'pattern2' ]
result = {}
for_each(regex_list) -> |i, pattern| {
parse_result = parse_regex_all!(to_string!(.http_status), pattern, numeric_groups: true)
if length(parse_result) > 0 {
result = set!(result, [i], parse_result)
}
}
. = result
```
Result
```
[[{ "0": "pattern1" }], [{ "0": "pattern2" }]]
```
> feat(parse_regex_all): allow variables for the 'pattern' parameter

- CHANGELOG.md
- lib/tests/tests/expressions/comparison/ge.vrl
- lib/tests/tests/expressions/comparison/gt.vrl
- lib/tests/tests/expressions/comparison/le.vrl
- lib/tests/tests/expressions/comparison/lt.vrl
- src/compiler/expression/op.rs
- src/compiler/value/arithmetic.rs
Support timestamp comparison using operators <, <=, >, >=.
> feat: support timestamp comparison

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
We don't seem to be using it and it causes a vulnerability to be flagged due to a dependency on an
old version of clap that depends on the unmaintained atty.
https://github.com/romankoblov/prettydiff/issues/18
> chore(deps): Remove prettydiff cli feature

- scripts/publish.py
It is easy to forget tagging.
Avoid human errors.
- Checks that the current version is not published
- Git tags after publishing
> chore: cargo publish script

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
The lack of this broke the VRL playground:
https://github.com/vectordotdev/vector/issues/19442
Regression introduced by
https://github.com/vectordotdev/vrl/pull/556
> fix(runtime): Re-add wasm features for chrono

- .github/dependabot.yml
- .github/workflows/changelog.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- changelog.d/194.enhancement.md
- changelog.d/README.md
- changelog.toml
- scripts/check_changelog_fragments.sh
- scripts/generate_release_changelog.sh
Adds a few scripts and a GH workflow to implement automated changelog generation at release time, using changelog fragments added during PRs.
See the `changelog.d/README.md` for details on the process.
Note that the filename of the fragment requires the PR number (i.e the fragment will be added after the PR is opened). While this could be seen as a DX pain, the existing process for adding entries to the "unreleased" section of the CHANGELOG.md, has the same pain (in order to get the PR link).
This could be enhanced in the future to have the GH workflow rename the fragment file that was added in the PR, to have the PR number.
When releasing VRL, the script `scripts/generate_release_changelog.sh` should be executed and a PR opened with the changes. That will convert all of the fragments …
> chore(releasing): automated changelog generation

- changelog.d/628.feature.md
- lib/tests/tests/functions/replace_with/capture_groups.vrl
- lib/tests/tests/functions/replace_with/captures_capture_group_name.vrl
- lib/tests/tests/functions/replace_with/error_in_closure.vrl
- lib/tests/tests/functions/replace_with/neg_count.vrl
- lib/tests/tests/functions/replace_with/string_capture_group_name.vrl
- lib/tests/tests/functions/replace_with/wrong_type.vrl
- lib/tests/tests/functions/replace_with/zero_count.vrl
- src/stdlib/mod.rs
- src/stdlib/replace_with.rs
This is similar to `replace`, but takes a closure to compute the replacment from the match and capture groups, instead of taking a replacment string.
Fixes: #628
> feat(stdlib): Add replace_with function

- .github/workflows/changelog.yaml
Since we want it to be a required check it needs to pass on merge queues.
> chore(ci): Run changelog check on merge queues

- benches/stdlib.rs
Missed in https://github.com/vectordotdev/vrl/pull/669
> chore(dev): Add benchmark for parse_etld

- Cargo.toml
- LICENSE-3rdparty.csv
- src/path/mod.rs
- src/path/owned.rs
- src/value/keystring.rs
Add property tests to ensure that arbitrary path values can be exported to strings and then re-parsed from that string to produce an equal path. This required some tweaks to the automatically generated `Arbitrary` implementations, and I added implementations of `FromStr` along the way to simplify parsing.
> Run proptests on paths

- Cargo.toml
- src/path/owned.rs
This is a series of incremental optimizations to the handling of exporting owned paths to strings. Mostly they are a process of eliminating intermediate `String` values and implementing the string conversion in terms of the `Display` implementations instead of the other way around.
FWIW I also did `Display` conversion for `OwnedValuePath` itself, but the underlying `serialize_field` function ended up with a looped `write!` of single characters, which seemed unlikely to be performant. Fixing that is probably more work than it's worth.
> Optimize path export functions

- lib/tests/tests/functions/parse_etld/etld_from_url.vrl
- lib/tests/tests/functions/parse_etld/etld_plus_one.vrl
- lib/tests/tests/functions/parse_etld/etld_plus_ten.vrl
- lib/tests/tests/functions/parse_etld/just_etld.vrl
- src/stdlib/parse_etld.rs
Missed in #669
This also adds `known_suffix` to type definition of `parse_etld` result, that was missed in original PR.
> Add missing VRL tests for `parse_etld`

- scripts/check_changelog_fragments.sh
This avoids the diff listing fragments that were deleted on master but still exist on the current branch.
> chore(ci): use merge-base in check for added changelog fragments

- .github/workflows/changelog.yaml
This is necessary so that the git command used in the workflow can find the merge base.
> chore(ci): checkout full depth in changelog workflow

- Cargo.toml
As requested here: https://github.com/vectordotdev/vrl/pull/671#discussion_r1479769824
Please add the no-changelog label to the PR.
Tested to pass the checks script.
Note that iana-time-zone is a dependency of the chrono crate, which is a dependency of the compiler and value features, so this crate is usually pulled in anyway, but this is definitely cleaner.
> Make iana-time-zone optional and behind stdlib flag

- changelog.d/709.feature.md
- src/stdlib/decode_punycode.rs
- src/stdlib/encode_punycode.rs
Adds additional optional argument to `encode_punycode` and `decode_punycode` that disables validation. This is useful in cases when it is not important if the result is a valid domain name. By default validation is enabled.
> feat(stdlib): add option to skip validation for punycode functions

- src/stdlib/decode_punycode.rs
- src/stdlib/encode_punycode.rs
I have implemented validation skip in #709, which ignores errors returned by `idna` crate when encoding and decoding punycode. One of the errors that it could return would result in output with missing sections (as was demonstrated in tests - e.g. `multiple_errors_ignore`). Since it is fairly trivial to split domain into parts (`idna` crate does it by doing split on `.`), we can split the domain ourselves in cases when we don't want validation and then try to encode ones that need encoding and leave them as they were if encoding (or decoding) fails.
Related: #709
> fix(stdlib): ensure punycode functions keep all input parts

- Cargo.toml
To allow for semantically versioned dependency equivalents. When trying to downgrade flate2 in Vector for testing it complained that the VRL crate required a newever version of flate2 since 1.0.28 restricts to >=1.0.28 and < 2.
> chore(deps): Relax version dependency constraints

- scripts/publish.py
crates.io has started returning 403s for the default requests user-agent. I'm guessing to avoid bot requests.
> chore: Set user-agent for publish script

- benches/stdlib.rs
- changelog.d/724.feature.md
- lib/tests/tests/functions/sieve/all_options.vrl
- lib/tests/tests/functions/sieve/characters.vrl
- lib/tests/tests/functions/sieve/regex.vrl
- src/stdlib/mod.rs
- src/stdlib/sieve.rs
Adds a `sieve` string function which can remove unwanted characters from a string using a list of allowed characters (or regex of allowed patterns).
Fixes: #704
> feat(stdlib): add `sieve` string function

- changelog.d/643.fix.md
- src/stdlib/log_util.rs
- src/stdlib/parse_nginx_log.rs
fixes #643 
The upstreaminfo log format regex was the odd one out on enforcing a non-empty referer. I've switched it to be the same as the others and use a * (0 or more) instead of a + (1 or more) non-" characters.
> fix(parse_nginx_log): allow empty referer in nginx logs (#643)

- changelog.d/725.breaking.md
- src/stdlib/parse_key_value.rs
Fixes #725 
Note: the key_value_parser no longer accepts empty keys!
This turned out to be a bit of a rabbit hole, but I tried to make minimal changes to meet fix the immediate issue.
I'm preserving some observed behavior that I've seen (in practice):
* escape sequences are not transformed
* there are no "invalid" escape sequences
* a wide range of keys parse successfully, such as lone quote characters `'` and backslashes `\`
However, I've made one change which may/may not be acceptable:
* empty keys no longer parse successfully
I'd like to think they have limited usefulness and actually indicate an error in the input, but it's up to you. It's simple enough to remove that validation (done using nom's verify() in `parse_key`) but some tests input start parsing weirdly instead of erroring. …
> fix(parse_key_value): handle more escapes (#725)

- Cargo.toml
- changelog.d/755.fix.md
- src/stdlib/parse_json.rs
Fixed by activating a feature in serde_json, see https://github.com/serde-rs/json/issues/536
For anyone somehow relying on the innaccurate/faster parsing of floats, it's technically a breaking change.
> fix(stdlib): parse_json improved accuracy float parsing #755

- src/stdlib/contains.rs
- src/stdlib/contains_all.rs
- src/stdlib/ends_with.rs
- src/stdlib/string_utils.rs
The parameter name was currently indicating the opposite of what it was doing.
Fixes: #802
> chore: Update parameter usage in convert_to_string

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- benches/stdlib.rs
- changelog.d/803.feature.md
- src/stdlib/mod.rs
- src/stdlib/uuid_from_friendly_id.rs
Resolves https://github.com/vectordotdev/vrl/issues/799
I've never written any Rust code before, so I recommend reviewing this carefully. It includes a passing test.
> Add uuid_from_friendly_id function

- Cargo.toml
- changelog.d/815.deprecation.md
- src/path/mod.rs
This adds a rate-limited deprecation warning that is output whenever a coalesce path is created (i.e. parsed). I thought it useful to put there to help identify _where_ such a path was being used.
Closes #678
> chore: Deprecate coalesce paths

- src/path/borrowed.rs
- src/path/mod.rs
For a long time, VRL has had a set of "owned" path types, but no corresponding types outside of `BorrowedSegment`. This makes it harder to name the actual type involved in borrows for implementing other traits.
This PR replaces the tuple types used for borrowed path with `BorrowedTargetPath` and `BorrowedValuePath`, mirroring their `Owned` equivalents. There is one deprecated implementation on the tuple types left in to allow Vector `master` branch to build as-is with these changes.
> chore: Introduce borrowed path types

- changelog.d/862.enhancement.md
- src/stdlib/parse_aws_alb_log.rs
Apparently AWS added new field to ALB log which broke our ingestion pipeline. Only place I found it is AWS Athena guide to parse ALB logs
https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html
Closes: https://github.com/vectordotdev/vrl/issues/852
> Add traceability_id field to alb log parse

- src/datadog/grok/lexer.rs
- src/datadog/grok/matchers/date.rs
- src/datadog/grok/parse_grok.rs
- src/datadog/grok/parse_grok_pattern.rs
- Fixes a case where a string in the grok pattern contains an escaped special character, followed by a non-ascii character.
- Extends `date` matcher to support patterns w/o zero-padding, e.g.: `%{date("M/d/yy HH:mm:ss z"):field}`
> fix(parse_groks): support multibyte characters and date matcher w/o zero-padding

- src/datadog/grok/matchers/date.rs
- src/datadog/grok/parse_grok.rs
- src/datadog/grok/parse_grok_rules.rs
Extends `date` [matcher](https://docs.datadoghq.com/service_management/events/pipelines_and_processors/grok_parser/?tab=matchers#parsing-dates):
- support other fraction characters, not only dot. Example: `%{date("M/d/yy HH:mm:ss,SSS z"):field}`
- support any number of fractional digits for patterns. Example: `%{date("M/d/yy HH:mm:ss.SSSS z"):field}`
> fix(datadog grok):  support more fraction of a second formats

- src/stdlib/dns_lookup.rs
- src/test/mod.rs
localhost doesn't seem to resolve consistently on MacOS causing test failures locally. Certainly there is some risk relying on dns.google but it seems minimal. We can swap it out with another domain if/as needed. Failures can be seen here: https://github.com/vectordotdev/vrl/pull/875
Also updates the VRL test runner to correctly diff objects.
Easier to review with whitespace changes disabled since I changed the indentation when updating the fixtures.
> chore(tests): Use dns.google in dns_lookup tests instead of localhost

- CHANGELOG.md
these were flagged in the 0.16 release, cleaning up the changelog manually for now
> chore(releasing): cleanup changelog.md of unneeded authors

- .github/workflows/test.yml
https://github.com/vectordotdev/vrl/pull/874 is fixing a recent example where the tests failed to run on MacOS. Add this CI check to catch it in the future.
This'll also help reduce the likelihood of VRL bugs on MacOS.
> chore(ci): Also run tests on MacOS

- src/cli/repl.rs
- src/compiler/compile_config.rs
- src/compiler/mod.rs
closes: https://github.com/vectordotdev/vector/issues/20840
This check is not useful in REPL mode. This PR disables the check only for REPL mode.
> fix(repl): do not check for unused expressions

- .github/dependabot.yml
Typically have to be upgraded together
> chore(ci): Group dependabot updates of prost libraries

- Cargo.toml
- src/datadog/search/node.rs
This adds support for serde serialization and deserialization for queries via their string representation, allowing them to be used directly in configurations without storing them in an intermediate `String`.
> chore(datadog search): Allow use of `QueryNode` in configurations

- Cargo.toml
I can't find a reason this needs to be restricted and it is prohibiting upgrades of indexmap in Vector.
> chore(deps): Relax constraint on indexmap

- .github/workflows/test.yml
- deny.toml
- scripts/check_deny.sh
This PR checks license compatibility using `cargo-deny` (updating the configuration) and also adds it as a CI check.
> chore(ci): Validate `cargo-deny` output in CI and check license compatibility

- Cargo.toml
Note that `stdlib.rs` benches require extra features and will not run with `cargo bench`. To run all benches, we can use `cargo bench --features="default test"`.
> chore(benches): remove redundant required features from some benches

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- benches/keyvalue.rs
- changelog.d/1015.enhancement.md
- src/datadog/grok/filters/keyvalue.rs
- src/datadog/grok/grok_filter.rs
- src/datadog/grok/parse_grok.rs
Extends `keyvalue` filter to match Datadog [implementation](https://docs.datadoghq.com/service_management/events/pipelines_and_processors/grok_parser/?tab=filters#key-value-or-logfmt).
> enhancement(datadog-grok): extend `keyvalue` filter to match Datadog implementation

- src/parser/ast.rs
- **Allow ast::Array and ast::Object to be built publicly**
- **Allow ast::Not nodes to be built publicly**
In order to make extra tooling around VRL (mostly to be able to add preprocessing tooling on top of existing language features), it would be nice to be able to build all AST node types outside the crate.
Most of the nodes can be built, except those three, so I assume it’s fine to add support there. I do not know why the inner elements were made private for these, so instead of making those public, I added the "obvious" general constructors I could think of for them.
Regards,
Gerry
> chore(ast): Allow all `parser::ast` nodes to be built publically

- changelog.d/1107.breaking.md
- src/compiler/conversion/mod.rs
- src/compiler/conversion/tests/mod.rs
Prior to this commit, string values that would exceed the f64 bounds would return `f64::INFINITY`. This leaks a type into the VRL scripts that could cause a panic without support to check for the value.
Fixes #1107
> fix(convert): return error when conversion exceeds f64 bounds

- changelog.d/1117.enhancement.md
- src/value/value.rs
Add `impl PartialOrd for Value`.
New feature.
No.
Add unit test that calls `partial_cmp` with different values.
> enhancement: Implement PartialOrd for Value

- changelog.d/1148.fix.md
- src/compiler/unused_expression_checker.rs
This modifies internal state and it's return value is always returns `null`. Should not expect result usage. 
This is true for all functions returning `null` so we could follow up with an enhancement to the unused expression detector.
Pointed Vector to this VRL branch and tested with:
```
sources:
demo_logs:
type: demo_logs
format: json
transforms:
remap:
type: remap
inputs: [demo_logs]
source: |
set_semantic_meaning(.foo, "a")
.foo = "bar"
sinks:
console:
type: console
inputs: [remap]
encoding:
codec: json
```
- Closes: https://github.com/vectordotdev/vrl/issues/1149
> fix(diagnostics): add 'set_semantic_meaning' to the side effects list

- .github/dependabot.yml
The main goal is to reduce KTLO noise. I don't see any strong downside.
> chore(ci): dependabot weekly schedule

- Cargo.lock
- Cargo.toml
Reverts vectordotdev/vrl#1175
This got merged with failing checks.
https://github.com/vectordotdev/vrl/actions/runs/12169161359/job/33941527890
Fixed by adding more checks:
> Revert "chore(deps): bump lalrpop from 0.20.2 to 0.22.0"

- changelog.d/1179.fix.md
- src/compiler/conversion/mod.rs
- src/compiler/conversion/tests/mod.rs
Reverts vectordotdev/vrl#1108
Due to https://github.com/vectordotdev/vector/issues/21970. We don't have numbers to prove this, but parsing `"0"` might be a common operation. And we don't want `parse_float` and `to_float` to diverge.
To err on the side of caution let's revert this change. We will work to provide safe arithemtic operations in the future (inspired by Rust APIs).
> fix(convert): Revert PR #1108 "return error when conversion exceeds f64 bounds"

- .github/ISSUE_TEMPLATE/minor-release.md
Documentation for the release process.
> docs(internal): Add template for releasing VRL

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/1179.fix.md
Cherry pick patch release commits.
https://github.com/vectordotdev/vector/issues/21992
> chore(releasing):  cherry pick v0.20.1 commits

- changelog.d/2893.fix.md
- lib/tests/tests/expressions/arithmetic/subtraction/nan_result.vrl
- src/compiler/value/arithmetic.rs
The `ordered_float` `sub` implementation panics for NaN results. 
Note that `inf` is a valid `f64` in Rust. In VRL we want to always throw an error for `NaN`s (at least this is the current status quo). 
Unit test and config:
```
api:
enabled: true
sources:
demo_logs_1:
type: demo_logs
format: json
transforms:
remap0:
type: remap
inputs: ["demo_logs_1"]
source: |
.a = to_float!("11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 …
```
> fix(sub): error instead of panic when subtraction yields NaN

- src/stdlib/encode_gzip.rs
- src/stdlib/encode_zlib.rs
- src/stdlib/encode_zstd.rs
- src/stdlib/find.rs
- src/stdlib/format_int.rs
- src/stdlib/format_number.rs
- src/stdlib/get.rs
- src/stdlib/match_datadog_query.rs
- src/stdlib/mod.rs
- src/stdlib/parse_etld.rs
- src/stdlib/parse_influxdb.rs
- src/stdlib/parse_int.rs
- src/stdlib/parse_json.rs
- src/stdlib/random_bytes.rs
- src/stdlib/remove.rs
- src/stdlib/replace.rs
- src/stdlib/replace_with.rs
- src/stdlib/set.rs
- src/stdlib/slice.rs
- src/stdlib/split.rs
- src/stdlib/to_float.rs
- src/stdlib/to_int.rs
- src/stdlib/truncate.rs
- src/stdlib/util.rs
- src/stdlib/uuid_v7.rs
- src/value/value/serde.rs
Part 3. Properly fixing the code around casts would be a breaking change. For now, I just removed the global `#[allow(...)]` blocks so that we don't introduce new code with these problems. 
Previous PR: https://github.com/vectordotdev/vrl/pull/1236
> chore(dev): more tricky clippy fixes

- changelog.d/1242.enhancement.md
- src/parsing/xml.rs
Small PR to make `parsing::xml::process_node` and its arguments public, to match VRL's XML processing for sibling use-cases.
Also re-exports the parts of [roxmltree](https://crates.io/crates/roxmltree) necessary to parse a _Document_ and operate against a _Node_.
```bash
./scripts/checks.sh
```
Note: since this PR simply changes the visibility of existing structs and functions, there should be no material impact.
N/A.
> chore(parsing): Make node processing in `parsing::xml` public

- Cargo.lock
- Cargo.toml
- changelog.d/1249.feature.md
- src/compiler/value/convert.rs
- src/datadog/grok/matchers/date.rs
- src/stdlib/format_timestamp.rs
- src/stdlib/parse_bytes.rs
- src/stdlib/parse_duration.rs
- src/stdlib/parse_json.rs
- src/stdlib/parse_regex.rs
- src/stdlib/parse_regex_all.rs
- src/stdlib/strlen.rs
- src/value/value.rs
- src/value/value/convert.rs
- src/value/value/serde.rs
This merge requests speeds up JSON parsing when `lossy` is set to true:
* it avoids double validation if bytes are valid UTF-8 string by using specific method from serde-json
* uses simdutf8 crate for faster UTF-8 validation
* this crate is already included when default features are on
* string validation by this crate is 4-11 times faster than Rust stdlib validation
* converting to lossy string can be slower in case string is not UTF-8 valid (it should be very rare)
Standard tests
> performance(stdlib,value): Faster JSON parsing

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/1188.breaking.md
- changelog.d/1221.feature.md
- changelog.d/1223.fix.md
- changelog.d/1246.breaking.md
- changelog.d/1247.feature.md
- changelog.d/1248.feature.md
- changelog.d/1249.feature.md
- changelog.d/1267.feature.md
- changelog.d/1280.fix.md
- release/create_release_pull_request.py
Generated with `./scripts/create-release-pull-request.py`.
Ref: https://github.com/vectordotdev/vector/issues/22445
> chore(releasing): Prepare 0.22.0 release

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
This simple change will remove 21 unnecessary dependencies.
Standard test case.
> chore(deps): Disable default features for rust_decimal to avoid deps

- Cargo.lock
- Cargo.toml
- src/compiler/value/arithmetic.rs
Reverts vectordotdev/vrl#1291 to unblock VRL updates for Vector.
We can proceed with this once we crypto crates upgrade to a newer `rand_core` version.
Explanation: https://github.com/vectordotdev/vector/pull/22558#issuecomment-2722275121
> chore(deps): revert bump `ordered-float` to 5.0.0

- .github/workflows/vector_integration_check.yaml
Follow up to https://github.com/vectordotdev/vrl/pull/1398.
Extracted commits from https://github.com/vectordotdev/vrl/pull/1399/files#diff-4f5c849c205cf3224b7c13fdcfc7f684e272f85f2a7a8aae17d5ce4a0d9a7036.
```
#!/bin/bash
set -euo pipefail
VRL_GITHUB_REPO="Zettroke/vrl"
VRL_GITHUB_BRANCH="apply-function-closure-type-info"
cat > Cargo.toml <<EOF
[dependencies]
vrl = { git = "https://github.com/vectordotdev/vrl.git", branch = "main", features = ["cli", "foo", sss] }
tokio = "1.0"
EOF
echo "🔧 Before:"
cat Cargo.toml
CARGO_TOML="Cargo.toml"
VRL_GITHUB_REPO="some_fork"
VRL_GITHUB_BRANCH="some_branch"
NEW_GIT="https://github.com/${VRL_GITHUB_REPO}.git"
NEW_BRANCH="${VRL_GITHUB_BRANCH}"
EXISTING_FEATURES=$(sed -nE 's/.*vrl = \{[^}]*features = (\[[^]]*\]).*/\1/p' "$CARGO_TOML")
if [[ -n …
```
> chore(ci): support branches from forks

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- changelog.d/1379.enhancement.md
- src/stdlib/decode_base64.rs
- src/stdlib/decode_lz4.rs
- src/stdlib/decode_mime_q.rs
- src/stdlib/decode_snappy.rs
- src/stdlib/encode_base64.rs
- src/stdlib/encode_lz4.rs
- src/stdlib/encode_snappy.rs
- src/stdlib/redact.rs
- src/stdlib/util.rs
Use SIMD instructions when doing base64 encoding/decoding. base64 encoding/decoding is common when processing logs, so it would be nice to use SIMD powered algo. `base64-simd` crate is already used by vector.
Standard tests.
> chore(performance): Use simd for base64 encoding/decoding

- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
Right now, `vrl` (and therefore, `vector`) fails to compile with GCC 15. This is due to `onig-sys` crate (which is a dependency of `onig` crate, which is a dependency of `grok` crate on which `vrl` depends)
Updating `grok` to `2.1.0` fixes this (https://github.com/mmastrac/grok/commit/9bf239475a735a4b02e13dbba0a48653a227afdf#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542)
More info here https://github.com/rust-onig/rust-onig/issues/195.
> chore: fix gcc 15 compile
