- .github/workflows/test.yml
> chore: add clippy check

- CHANGELOG.md
- CONTRIBUTING.md
A changelog will be used to track changes for each version. A `CONTRIBUTING.md` was added, with the requirement to add changes to the `CHANGELOG.md` file.
> chore: Add initial changelog / contributing guide

- .github/workflows/gardener_open_issue.yml
- .github/workflows/gardener_open_pr.yml
- .github/workflows/gardener_remove_waiting_author.yml
closes https://github.com/vectordotdev/vrl/issues/155
The `secrets.GH_PROJECT_PAT` secret has been added to the repo.
> chore: add gardener workflows

- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
Closes #166
Also needs the repo settings updated
> update default branch to main

- LICENSE-3rdparty.csv
Seems to have fallen out of sync
> chore: Regenerate LICENSE-3rdparty.csv

- Cargo.toml
- src/path/mod.rs
This is a small first step in the context of https://github.com/vectordotdev/vector/issues/13033.
> chore: Add string_path feature

- src/compiler/expression/query.rs
> fix: fix query display metadata write

- CHANGELOG.md
Hello,
Apologies, I forgot to update the changelog as part of https://github.com/vectordotdev/vrl/pull/360, this fixes that!
> Added community_id function to the changelog

- scripts/checks.sh
Can now pick and choose what to run e.g. `./scripts/checks.sh clippy tests vrl_tests`.
Also, added help argument.
> chore: small improvement to checks.sh

- src/compiler/deprecation_warning.rs
> chore: Add version to deprecation warnings

- .github/workflows/test.yml
- Cargo.toml
- scripts/check_msrv.sh
> chore: Add MSRV

- src/compiler/datetime.rs
To aid easier conversion of VRL's TimeZone to FixedOffset as requested in https://github.com/vectordotdev/vector/pull/18506
> Enhancement: Conversion for TimeZone to FixedOffset

- src/compiler/expression/array.rs
- src/compiler/expression/block.rs
- src/compiler/expression/function_call.rs
- src/compiler/expression/not.rs
- src/compiler/expression/object.rs
- src/compiler/expression/op.rs
- src/compiler/type_def.rs
- src/stdlib/boolean.rs
- src/stdlib/chunks.rs
- src/stdlib/contains_all.rs
- src/stdlib/encode_gzip.rs
- src/stdlib/encode_key_value.rs
- src/stdlib/encode_zlib.rs
- src/stdlib/float.rs
- src/stdlib/integer.rs
- src/stdlib/slice.rs
- src/stdlib/string.rs
- src/stdlib/timestamp.rs
- src/stdlib/to_bool.rs
- src/stdlib/to_float.rs
- src/stdlib/to_int.rs
- src/stdlib/to_string.rs
closes: https://github.com/vectordotdev/vrl/issues/32
> feat: fallibility is now an enum

- CHANGELOG.md
- src/stdlib/parse_json.rs
- src/value/value.rs
- src/value/value/serde.rs
> fix!(parse_json): (lossy) convert large numbers to float to avoid int overflow

- lib/tests/src/main.rs
- lib/tests/tests/diagnostics/truncate_deprecated_argument.vrl
- src/test/mod.rs
- src/test/test.rs
Stumbled upon this while working on another branch (unused expression warnings).
* sanitize warning/error strings
* respect `skip` flag 
* print warnings counter
> chore(test): refactor VRL test runner

- Cargo.lock
- src/stdlib/parse_klog.rs
- src/stdlib/parse_linux_authorization.rs
ref: https://github.com/vectordotdev/vrl/issues/8
> chore(tests): fix 2024 year

- scripts/publish.py
The purpose of this PR is to add an extra sanity check before publishing a new VRL version.
> chore: update publish script to check if there are fragments

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/633.enhancement.md
- changelog.d/669.feature.md
- changelog.d/671.enhancement.md
- changelog.d/672.feature.md
- changelog.d/679.fix.md
> chore(releasing): Prepare 0.11.0 release

- rust-toolchain.toml
- src/compiler/expression/function_call.rs
- src/value/keystring.rs
> chore(deps): Bump Rust toolchain to v1.75

- rust-toolchain.toml
- src/compiler/expression/assignment.rs
- src/stdlib/log.rs
- src/test/mod.rs
- src/test/test.rs
- src/value/kind/collection.rs
- src/value/secrets.rs
Update Rust version used for local development and testing to 1.78.
> chore(deps): Update Rust to 1.78

- .github/dependabot.yml
Inspired by https://github.com/vectordotdev/vector/pull/21595
> chore(ci): group Dependabot patch updates

- Cargo.toml
> chore(dev): format Cargo.toml

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/1079.fix.md
- changelog.d/1100.feature.md
- changelog.d/1104.enhancement.md
- changelog.d/1107.breaking.md
- changelog.d/1114.fix.md
- changelog.d/1115.fix.md
- changelog.d/1117.enhancement.md
- changelog.d/1148.fix.md
* Bumped version
* Ran `./scripts/generate_release_changelog.sh`
https://github.com/vectordotdev/vector/issues/21893
> chore(releasing): Prepare VRL v0.20.0

- Cargo.lock
- LICENSE-3rdparty.csv
Updates `hashbrown` and `anstream` to fix vulnerabilities. 
`cargo deny -L error check`
> chore(deps): Update anstream and hashbrown to fix vulnerabilities reported by `cargo deny`

- Cargo.lock
- LICENSE-3rdparty.csv
Ran `cargo update`
`cargo clippy`
> chore(deps): Update all transitive dependencies

- rust-toolchain.toml
- src/compiler/conversion/mod.rs
- src/core/encode_key_value.rs
- src/datadog/grok/filters/array.rs
- src/datadog/grok/filters/keyvalue.rs
- src/datadog/grok/lexer.rs
- src/datadog/grok/parse_grok_rules.rs
- src/diagnostic/formatter.rs
- src/path/mod.rs
- src/stdlib/decode_mime_q.rs
- src/stdlib/encode_punycode.rs
- src/stdlib/parse_aws_alb_log.rs
- src/stdlib/starts_with.rs
- src/value/value/iter.rs
Bump the Rust toolchain to latest (1.83). Will unblock https://github.com/vectordotdev/vrl/pull/1128.
`cargo clippy`
> chore(deps): Bump Rust toolchain to 1.83.0

- .github/dependabot.yml
Dependabot allow all 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
> chore(ci): dependabot allow all dep types

- Cargo.toml
Raise MSVC to 1.80 to favor `Duration::div_duration_f64` method in #1197 .
#1197
> Bump MSRV to 1.80

- CONTRIBUTING.md
A few enhancements to the contribution guide.
> docs(external): CONTRIBUTING.md enhancements

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/1136.feature.md
- changelog.d/1152.feature.md
- changelog.d/1158.feature.md
- changelog.d/1162.feature.md
- changelog.d/1164.feature.md
- changelog.d/1197.feature.md
- changelog.d/1198.feature.md
- changelog.d/1202.feature.md
- changelog.d/1207.feature.md
- changelog.d/2893.fix.md
- changelog.d/979.breaking.md
Ref: https://github.com/vectordotdev/vector/issues/22152
> chore(releasing): bump VRL version to 0.21.0

- src/stdlib/compact.rs
- src/stdlib/crc.rs
- src/stdlib/format_number.rs
- src/stdlib/from_unix_timestamp.rs
- src/stdlib/hmac.rs
- src/stdlib/ip_subnet.rs
- src/stdlib/log.rs
- src/stdlib/log_util.rs
- src/stdlib/map_values.rs
- src/stdlib/mod.rs
- src/stdlib/parse_apache_log.rs
- src/stdlib/parse_aws_alb_log.rs
- src/stdlib/parse_common_log.rs
- src/stdlib/parse_json.rs
- src/stdlib/parse_key_value.rs
- src/stdlib/parse_nginx_log.rs
- src/stdlib/redact.rs
- src/stdlib/remove.rs
- src/stdlib/set.rs
- src/stdlib/starts_with.rs
- src/stdlib/to_bool.rs
- src/stdlib/unnest.rs
`src/stdlib/mod.rs` ignored a lot of clippy warnings. I am going to progressively fix them to improve code quality and catch these early when new functions are added.
> chore(dev): clippy fixes

- src/stdlib/assert.rs
- src/stdlib/compact.rs
- src/stdlib/encode_percent.rs
- src/stdlib/log.rs
- src/stdlib/map_values.rs
- src/stdlib/mod.rs
- src/stdlib/parse_aws_alb_log.rs
- src/stdlib/parse_cef.rs
- src/stdlib/parse_key_value.rs
- src/stdlib/parse_nginx_log.rs
- src/stdlib/parse_syslog.rs
- src/stdlib/string_utils.rs
Part 2.
First PR: https://github.com/vectordotdev/vrl/pull/1234
> chore(dev): more clippy fixes

- src/stdlib/from_unix_timestamp.rs
- src/stdlib/mod.rs
- src/stdlib/parse_apache_log.rs
- src/stdlib/parse_glog.rs
- src/stdlib/parse_klog.rs
- src/stdlib/parse_syslog.rs
- src/stdlib/tag_types_externally.rs
- src/stdlib/to_float.rs
- src/stdlib/to_unix_timestamp.rs
Part 4. 
Previous PR: https://github.com/vectordotdev/vrl/pull/1237
> chore(dev): fix deprecations

- changelog.d/1247.feature.md
- lib/tests/tests/diagnostics/cant_abort_infallible_function.vrl
- src/compiler/compiler.rs
- src/compiler/expression/function_call.rs
- src/compiler/mod.rs
We should downgrade harmless errors to warnings to reduce friction for VRL users. This PR addresses one of the most common errors "can't abort infallible function".  Long term, we want to introduce a strict mode for users to turn on/off.
- Closes: https://github.com/vectordotdev/vrl/issues/1143#issue-2695155422
> chore(compiler): downgrade common abort-infallible error to a warning

- benches/stdlib.rs
- src/cli/cmd.rs
- src/cli/mod.rs
- src/cli/repl.rs
- src/compiler/compiler.rs
- src/compiler/conversion/tests/mod.rs
- src/compiler/expression/assignment.rs
- src/compiler/expression/function_call.rs
- src/compiler/expression/if_statement.rs
- src/compiler/expression/levenstein.rs
- src/compiler/expression/op.rs
- src/compiler/expression_error.rs
- src/compiler/mod.rs
- src/compiler/runtime.rs
- src/compiler/state.rs
- src/compiler/type_def.rs
- src/compiler/unused_expression_checker.rs
- src/compiler/value/arithmetic.rs
- src/core/mod.rs
- src/test/mod.rs
Another batch of clippy fixes.
> chore(dev): enable even more clippy/lint checks

- README.md
Trivial PR, skipping review template.
> chore(docs): add test feature to README.md

- src/protobuf/encode.rs
* Use simdutf8 for converting bytes to string 
* Do not allocate new string when it is not necessary 
Standard test cases
> performance(protobuf): Optimise converting to protobuf

- release/create_release_pull_request.py
- scripts/generate_release_changelog.sh
> chore(releasing): add `--no-prompt` support for generate_release_changelog.sh

- Cargo.toml
This dependency is not required by all features.
> fix(dev): make `encoding_rs` optional

- rust-toolchain.toml
Follow up after bumping this on Vector.
> chore(deps): bump rust toolchain to 1.85

- Cargo.lock
- Cargo.toml
Less dependencies means less problems and shorter compilation time.
Standard tests
> chore(deps): Removed unused toml dev dependency

- build.rs
The `read_grok_patterns` build script function uses `std::fs::read_dir` to read grok patterns from the `src/datadog/grok/patterns` directory and creates the `pattern.rs` file from them.
As mentioned in the [`std::fs::read_dir`](https://doc.rust-lang.org/stable/std/fs/fn.read_dir.html) documentation, "the order in which this iterator returns entries is platform and filesystem dependent", which means that the order of the entries in the resulting `pattern.rs` may be different for the same platform on a different filesystem. Since the patterns end up in the final binary, this poses a reproducibility problem.
To mitigate this problem, this change sorts the result of `std::fs::read_dir` before creating `pattern.rs`.
our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d …
> chore(build script): sort grok pattern file names

- src/compiler/mod.rs
- src/compiler/test_util.rs
This will allow the use of test macros in Vector.
> chore(deps): import paste directly

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
VRL can benefit from bug and enhancement issue templates. These are similar to the Vector templates.
> chore(dev): Add bug and feature request templates

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- LICENSE-3rdparty.csv
- src/stdlib/random_bool.rs
- src/stdlib/random_bytes.rs
- src/stdlib/random_float.rs
- src/stdlib/random_int.rs
Reverts vectordotdev/vrl#1300
Unblocks: https://github.com/vectordotdev/vector/pull/22668
Ref: 
* https://github.com/vectordotdev/vector/pull/22558#issuecomment-2722275121
* https://github.com/vectordotdev/vrl/pull/1338
> chore(deps): revert of "bump rand and uuid"

- Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2025-0023
> fix(deps): update tokio - RUSTSEC-2025-0023

- .github/dependabot.yml
Updating monthly is reasonable and reduces KTLO.
> chore(ci): update interval changed to 'monthly'

- scripts/ensure-wasm-pack-installed.sh
https://github.com/vectordotdev/vector/blob/master/scripts/environment/prepare.sh#L24-L29
> chore(ci): update wasm-pack to 0.13.1 (same with Vector)

- Cargo.lock
- Cargo.toml
In the future, to prevent this, we should try a `cargo check` on Vector while pointing to the VRL PR branch.
> fix(deps): revert to previous prost-reflect - Vector compatibility

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- changelog.d/1301.enhancement.md
- changelog.d/1370.fix.md
- changelog.d/1379.enhancement.md
Generated with create_release_pull_request.py
> chore(releasing): Prepare 0.24.0 release

- rust-toolchain.toml
- src/compiler/expression/assignment.rs
- src/compiler/expression/function_call.rs
- src/compiler/expression/op.rs
- src/compiler/runtime.rs
- src/core/encode_key_value.rs
- src/parser/lex.rs
- src/path/jit.rs
- src/stdlib/decode_mime_q.rs
- src/stdlib/for_each.rs
- src/stdlib/parse_glog.rs
- src/stdlib/remove.rs
- src/stdlib/set.rs
- src/value/kind/collection/unknown.rs
- src/value/kind/comparison.rs
- src/value/kind/crud/insert.rs
- src/value/kind/merge.rs
- src/value/value/iter.rs
> chore(deps): bump rust toolchain to 1.86

- src/path/owned.rs
Simplify and test `to_alternative_components`. It was previously returning a `Vec<Vec<&str>>` when a simple `Vec<&str>` would suffice. It was also untested
`cargo test`
> chore(path): Simplify and test `to_alternative_components`

- src/datadog/filter/matcher.rs
This just moves the implementation of `build_matcher` inside an `impl QueryNode` block and then wraps it with a top-level function for backwards compatibility.
(Best viewed with "Hide whitespace")
> chore(datadog_search): Export `build_matcher` as a method on `QueryNode`

- Cargo.toml
> chore(deps): unpin grok patch version

- rust-toolchain.toml
- src/compiler/expression/function_call.rs
- src/parser/lex.rs
> chore(dev): update rust toolchain to 1.90
